[tox]
envlist = py37,py38,py39,py310,py311,py312,py313,py314,pypy3
requires = tox-uv

[testenv]
changedir = .tox
dependency_groups = dev
commands = pytest --doctest-modules {env_site_packages_dir}/boltons {tox_root}/tests {posargs}
