name: Tests
on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "*.rst"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "*.rst"
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: Linux, python: "3.14", os: ubuntu-latest, tox: py314 }
          - { name: Windows, python: "3.14", os: windows-latest, tox: py314 }
          - { name: Mac, python: "3.14", os: macos-latest, tox: py314 }
          - { name: "3.13", python: "3.13", os: ubuntu-latest, tox: py313 }
          - { name: "3.12", python: "3.12", os: ubuntu-latest, tox: py312 }
          - { name: "3.11", python: "3.11", os: ubuntu-latest, tox: py311 }
          - { name: "3.10", python: "3.10", os: ubuntu-latest, tox: py310 }
          - { name: "3.9", python: "3.9", os: ubuntu-latest, tox: py39 }
          - { name: "3.8", python: "3.8", os: ubuntu-latest, tox: py38 }
          - { name: "3.7", python: "3.7", os: ubuntu-22.04, tox: py37 }
          - { name: "PyPy3", python: "pypy-3.9", os: ubuntu-latest, tox: pypy3 }
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      - run: uvx --with tox-uv tox -e ${{ matrix.tox }}
